/**
 * India location dataset — 28 states + 8 UTs with officially-normalised district
 * lists, plus the 48 UPSC CMS exam centres. Ported verbatim from the live web
 * `js/location-data.js` (single source of truth). The whole dataset is bundled;
 * these are pure data + lookup helpers with no I/O and no DOM (the web
 * `populate*Select` / `wireDistrictCascade` DOM helpers are intentionally NOT
 * ported — RN pickers read the arrays directly).
 *
 * Column-spelling quirk mirrors the backend: `exam_center` (US, free text) vs
 * `exam_centre_state` / `exam_centre_district` (UK). For UPSC CMS the centre name
 * is stored in `exam_centre_district` and its parent state in `exam_centre_state`.
 */

// ─── States & Union Territories (28 states, then 8 UTs; both alphabetical) ────
export const STATES: string[] = [
  // States
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  // Union Territories
  'Andaman & Nicobar Islands',
  'Chandigarh',
  'Dadra & Nagar Haveli and Daman & Diu',
  'Delhi',
  'Jammu & Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

// ─── Districts by State / UT ──────────────────────────────────────────────────
export const DISTRICTS_BY_STATE: Record<string, string[]> = {
  // Andhra Pradesh (26 districts — April 2022 reorganisation)
  'Andhra Pradesh': [
    'Alluri Sitharama Raju',
    'Anakapalli',
    'Anantapur',
    'Annamayya',
    'Bapatla',
    'Chittoor',
    'Dr. B.R. Ambedkar Konaseema',
    'East Godavari',
    'Eluru',
    'Guntur',
    'Kakinada',
    'Krishna',
    'Kurnool',
    'Nandyal',
    'NTR',
    'Palnadu',
    'Parvathipuram Manyam',
    'Prakasam',
    'Sri Potti Sriramulu Nellore',
    'Sri Sathya Sai',
    'Srikakulam',
    'Tirupati',
    'Visakhapatnam',
    'Vizianagaram',
    'West Godavari',
    'YSR Kadapa',
  ],

  // Arunachal Pradesh (26 districts)
  'Arunachal Pradesh': [
    'Anjaw',
    'Changlang',
    'Dibang Valley',
    'East Kameng',
    'East Siang',
    'Kamle',
    'Kra Daadi',
    'Kurung Kumey',
    'Lepa Rada',
    'Lohit',
    'Longding',
    'Lower Dibang Valley',
    'Lower Siang',
    'Lower Subansiri',
    'Namsai',
    'Pakke-Kessang',
    'Papum Pare',
    'Shi Yomi',
    'Siang',
    'Tawang',
    'Tirap',
    'Upper Dibang Valley',
    'Upper Siang',
    'Upper Subansiri',
    'West Kameng',
    'West Siang',
  ],

  // Assam (35 districts)
  'Assam': [
    'Bajali',
    'Baksa',
    'Barpeta',
    'Biswanath',
    'Bongaigaon',
    'Cachar',
    'Charaideo',
    'Chirang',
    'Darrang',
    'Dhemaji',
    'Dhubri',
    'Dibrugarh',
    'Dima Hasao',
    'Goalpara',
    'Golaghat',
    'Hailakandi',
    'Hojai',
    'Jorhat',
    'Kamrup',
    'Kamrup Metropolitan',
    'Karbi Anglong',
    'Karimganj',
    'Kokrajhar',
    'Lakhimpur',
    'Majuli',
    'Morigaon',
    'Nagaon',
    'Nalbari',
    'Sivasagar',
    'Sonitpur',
    'South Salmara-Mankachar',
    'Tamulpur',
    'Tinsukia',
    'Udalguri',
    'West Karbi Anglong',
  ],

  // Bihar (38 districts)
  'Bihar': [
    'Araria',
    'Arwal',
    'Aurangabad',
    'Banka',
    'Begusarai',
    'Bhagalpur',
    'Bhojpur',
    'Buxar',
    'Darbhanga',
    'East Champaran',
    'Gaya',
    'Gopalganj',
    'Jamui',
    'Jehanabad',
    'Kaimur',
    'Katihar',
    'Khagaria',
    'Kishanganj',
    'Lakhisarai',
    'Madhepura',
    'Madhubani',
    'Munger',
    'Muzaffarpur',
    'Nalanda',
    'Nawada',
    'Patna',
    'Purnia',
    'Rohtas',
    'Saharsa',
    'Samastipur',
    'Saran',
    'Sheikhpura',
    'Sheohar',
    'Sitamarhi',
    'Siwan',
    'Supaul',
    'Vaishali',
    'West Champaran',
  ],

  // Chhattisgarh (33 districts)
  'Chhattisgarh': [
    'Balod',
    'Baloda Bazar',
    'Balrampur-Ramanujganj',
    'Bastar',
    'Bemetara',
    'Bijapur',
    'Bilaspur',
    'Dantewada',
    'Dhamtari',
    'Durg',
    'Gariaband',
    'Gaurela-Pendra-Marwahi',
    'Janjgir-Champa',
    'Jashpur',
    'Kabirdham',
    'Kanker',
    'Khairagarh-Chhuikhadan-Gandai',
    'Kondagaon',
    'Korba',
    'Koriya',
    'Mahasamund',
    'Manendragarh-Chirmiri-Bharatpur',
    'Mohla-Manpur-Ambagarh Chowki',
    'Mungeli',
    'Narayanpur',
    'Raigarh',
    'Raipur',
    'Rajnandgaon',
    'Sakti',
    'Sarangarh-Bilaigarh',
    'Sukma',
    'Surajpur',
    'Surguja',
  ],

  // Goa (2 districts)
  'Goa': [
    'North Goa',
    'South Goa',
  ],

  // Gujarat (33 districts)
  'Gujarat': [
    'Ahmedabad',
    'Amreli',
    'Anand',
    'Aravalli',
    'Banaskantha',
    'Bharuch',
    'Bhavnagar',
    'Botad',
    'Chhota Udaipur',
    'Dahod',
    'Dang',
    'Devbhumi Dwarka',
    'Gandhinagar',
    'Gir Somnath',
    'Jamnagar',
    'Junagadh',
    'Kheda',
    'Kutch',
    'Mahisagar',
    'Mehsana',
    'Morbi',
    'Narmada',
    'Navsari',
    'Panchmahal',
    'Patan',
    'Porbandar',
    'Rajkot',
    'Sabarkantha',
    'Surat',
    'Surendranagar',
    'Tapi',
    'Vadodara',
    'Valsad',
  ],

  // Haryana (22 districts)
  'Haryana': [
    'Ambala',
    'Bhiwani',
    'Charkhi Dadri',
    'Faridabad',
    'Fatehabad',
    'Gurugram',
    'Hisar',
    'Jhajjar',
    'Jind',
    'Kaithal',
    'Karnal',
    'Kurukshetra',
    'Mahendragarh',
    'Nuh',
    'Palwal',
    'Panchkula',
    'Panipat',
    'Rewari',
    'Rohtak',
    'Sirsa',
    'Sonipat',
    'Yamunanagar',
  ],

  // Himachal Pradesh (12 districts)
  'Himachal Pradesh': [
    'Bilaspur',
    'Chamba',
    'Hamirpur',
    'Kangra',
    'Kinnaur',
    'Kullu',
    'Lahaul & Spiti',
    'Mandi',
    'Shimla',
    'Sirmaur',
    'Solan',
    'Una',
  ],

  // Jharkhand (24 districts)
  'Jharkhand': [
    'Bokaro',
    'Chatra',
    'Deoghar',
    'Dhanbad',
    'Dumka',
    'East Singhbhum',
    'Garhwa',
    'Giridih',
    'Godda',
    'Gumla',
    'Hazaribagh',
    'Jamtara',
    'Khunti',
    'Koderma',
    'Latehar',
    'Lohardaga',
    'Pakur',
    'Palamu',
    'Ramgarh',
    'Ranchi',
    'Sahebganj',
    'Seraikela Kharsawan',
    'Simdega',
    'West Singhbhum',
  ],

  // Karnataka (31 districts)
  'Karnataka': [
    'Bagalkote',
    'Ballari',
    'Belagavi',
    'Bengaluru Rural',
    'Bengaluru Urban',
    'Bidar',
    'Chamarajanagar',
    'Chikballapur',
    'Chikkamagaluru',
    'Chitradurga',
    'Dakshina Kannada',
    'Davangere',
    'Dharwad',
    'Gadag',
    'Hassan',
    'Haveri',
    'Kalaburagi',
    'Kodagu',
    'Kolar',
    'Koppal',
    'Mandya',
    'Mysuru',
    'Raichur',
    'Ramanagara',
    'Shivamogga',
    'Tumakuru',
    'Udupi',
    'Uttara Kannada',
    'Vijayapura',
    'Vijayanagara',
    'Yadgir',
  ],

  // Kerala (14 districts)
  'Kerala': [
    'Alappuzha',
    'Ernakulam',
    'Idukki',
    'Kannur',
    'Kasaragod',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Malappuram',
    'Palakkad',
    'Pathanamthitta',
    'Thiruvananthapuram',
    'Thrissur',
    'Wayanad',
  ],

  // Madhya Pradesh (55 districts — incl. 3 new in 2023)
  'Madhya Pradesh': [
    'Agar Malwa',
    'Alirajpur',
    'Anuppur',
    'Ashoknagar',
    'Balaghat',
    'Barwani',
    'Betul',
    'Bhind',
    'Bhopal',
    'Burhanpur',
    'Chhatarpur',
    'Chhindwara',
    'Damoh',
    'Datia',
    'Dewas',
    'Dhar',
    'Dindori',
    'Guna',
    'Gwalior',
    'Harda',
    'Indore',
    'Jabalpur',
    'Jhabua',
    'Katni',
    'Khandwa',
    'Khargone',
    'Maihar',
    'Mandla',
    'Mandsaur',
    'Morena',
    'Mauganj',
    'Narsinghpur',
    'Neemuch',
    'Niwari',
    'Narmadapuram',
    'Pandhurna',
    'Panna',
    'Raisen',
    'Rajgarh',
    'Ratlam',
    'Rewa',
    'Sagar',
    'Satna',
    'Sehore',
    'Seoni',
    'Shahdol',
    'Shajapur',
    'Sheopur',
    'Shivpuri',
    'Sidhi',
    'Singrauli',
    'Tikamgarh',
    'Ujjain',
    'Umaria',
    'Vidisha',
  ],

  // Maharashtra (36 districts)
  'Maharashtra': [
    'Ahmednagar',
    'Akola',
    'Amravati',
    'Aurangabad',
    'Beed',
    'Bhandara',
    'Buldhana',
    'Chandrapur',
    'Dhule',
    'Gadchiroli',
    'Gondia',
    'Hingoli',
    'Jalgaon',
    'Jalna',
    'Kolhapur',
    'Latur',
    'Mumbai City',
    'Mumbai Suburban',
    'Nagpur',
    'Nanded',
    'Nandurbar',
    'Nashik',
    'Osmanabad',
    'Palghar',
    'Parbhani',
    'Pune',
    'Raigad',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sindhudurg',
    'Solapur',
    'Thane',
    'Wardha',
    'Washim',
    'Yavatmal',
  ],

  // Manipur (16 districts)
  'Manipur': [
    'Bishnupur',
    'Chandel',
    'Churachandpur',
    'Imphal East',
    'Imphal West',
    'Jiribam',
    'Kakching',
    'Kamjong',
    'Kangpokpi',
    'Noney',
    'Pherzawl',
    'Senapati',
    'Tamenglong',
    'Tengnoupal',
    'Thoubal',
    'Ukhrul',
  ],

  // Meghalaya (12 districts)
  'Meghalaya': [
    'East Garo Hills',
    'East Jaintia Hills',
    'East Khasi Hills',
    'Eastern West Khasi Hills',
    'North Garo Hills',
    'Ri Bhoi',
    'South Garo Hills',
    'South West Garo Hills',
    'South West Khasi Hills',
    'West Garo Hills',
    'West Jaintia Hills',
    'West Khasi Hills',
  ],

  // Mizoram (11 districts)
  'Mizoram': [
    'Aizawl',
    'Champhai',
    'Hnahthial',
    'Khawzawl',
    'Kolasib',
    'Lawngtlai',
    'Lunglei',
    'Mamit',
    'Saiha',
    'Saitual',
    'Serchhip',
  ],

  // Nagaland (16 districts — incl. Chumoukedima & Niuland 2022)
  'Nagaland': [
    'Chumoukedima',
    'Dimapur',
    'Kiphire',
    'Kohima',
    'Longleng',
    'Mokokchung',
    'Mon',
    'Niuland',
    'Noklak',
    'Peren',
    'Phek',
    'Shamator',
    'Tseminyü',
    'Tuensang',
    'Wokha',
    'Zunheboto',
  ],

  // Odisha (30 districts)
  'Odisha': [
    'Angul',
    'Balangir',
    'Balasore',
    'Bargarh',
    'Bhadrak',
    'Boudh',
    'Cuttack',
    'Deogarh',
    'Dhenkanal',
    'Gajapati',
    'Ganjam',
    'Jagatsinghpur',
    'Jajpur',
    'Jharsuguda',
    'Kalahandi',
    'Kandhamal',
    'Kendrapara',
    'Keonjhar',
    'Khordha',
    'Koraput',
    'Malkangiri',
    'Mayurbhanj',
    'Nabarangpur',
    'Nayagarh',
    'Nuapada',
    'Puri',
    'Rayagada',
    'Sambalpur',
    'Subarnapur',
    'Sundargarh',
  ],

  // Punjab (23 districts — incl. Malerkotla 2021)
  'Punjab': [
    'Amritsar',
    'Barnala',
    'Bathinda',
    'Faridkot',
    'Fatehgarh Sahib',
    'Fazilka',
    'Ferozepur',
    'Gurdaspur',
    'Hoshiarpur',
    'Jalandhar',
    'Kapurthala',
    'Ludhiana',
    'Malerkotla',
    'Mansa',
    'Moga',
    'Mohali',
    'Sri Muktsar Sahib',
    'Pathankot',
    'Patiala',
    'Rupnagar',
    'Sangrur',
    'Shahid Bhagat Singh Nagar',
    'Tarn Taran',
  ],

  // Rajasthan (50 districts — August 2023 reorganisation)
  'Rajasthan': [
    'Ajmer',
    'Alwar',
    'Anupgarh',
    'Balotra',
    'Banswara',
    'Baran',
    'Barmer',
    'Beawar',
    'Bharatpur',
    'Bhilwara',
    'Bikaner',
    'Bundi',
    'Chittorgarh',
    'Churu',
    'Dausa',
    'Deeg',
    'Dholpur',
    'Didwana-Kuchaman',
    'Dudu',
    'Dungarpur',
    'Gangapur City',
    'Hanumangarh',
    'Jaipur',
    'Jaipur Rural',
    'Jaisalmer',
    'Jalore',
    'Jhalawar',
    'Jhunjhunu',
    'Jodhpur',
    'Jodhpur Rural',
    'Karauli',
    'Kekri',
    'Khairthal-Tijara',
    'Kota',
    'Kotputli-Behror',
    'Nagaur',
    'Neem Ka Thana',
    'Pali',
    'Phalodi',
    'Pratapgarh',
    'Rajsamand',
    'Salumbar',
    'Sanchore',
    'Sawai Madhopur',
    'Shahpura',
    'Sikar',
    'Sirohi',
    'Sri Ganganagar',
    'Tonk',
    'Udaipur',
  ],

  // Sikkim (6 districts — incl. Pakyong & Soreng 2022)
  'Sikkim': [
    'East Sikkim',
    'North Sikkim',
    'Pakyong',
    'South Sikkim',
    'Soreng',
    'West Sikkim',
  ],

  // Tamil Nadu (38 districts — incl. Mayiladuthurai 2020)
  'Tamil Nadu': [
    'Ariyalur',
    'Chengalpattu',
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Kallakurichi',
    'Kancheepuram',
    'Kanniyakumari',
    'Karur',
    'Krishnagiri',
    'Madurai',
    'Mayiladuthurai',
    'Nagapattinam',
    'Namakkal',
    'Nilgiris',
    'Perambalur',
    'Pudukkottai',
    'Ramanathapuram',
    'Ranipet',
    'Salem',
    'Sivaganga',
    'Tenkasi',
    'Thanjavur',
    'Theni',
    'Thoothukudi',
    'Tiruchirappalli',
    'Tirunelveli',
    'Tirupathur',
    'Tiruppur',
    'Tiruvallur',
    'Tiruvannamalai',
    'Tiruvarur',
    'Vellore',
    'Viluppuram',
    'Virudhunagar',
  ],

  // Telangana (33 districts — 2022 reorganisation)
  'Telangana': [
    'Adilabad',
    'Bhadradri Kothagudem',
    'Hanumakonda',
    'Hyderabad',
    'Jagtial',
    'Jangaon',
    'Jayashankar Bhupalpally',
    'Jogulamba Gadwal',
    'Kamareddy',
    'Karimnagar',
    'Khammam',
    'Kumuram Bheem Asifabad',
    'Mahabubabad',
    'Mahabubnagar',
    'Mancherial',
    'Medak',
    'Medchal-Malkajgiri',
    'Mulugu',
    'Nagarkurnool',
    'Nalgonda',
    'Narayanpet',
    'Nirmal',
    'Nizamabad',
    'Peddapalli',
    'Rajanna Sircilla',
    'Rangareddy',
    'Sangareddy',
    'Siddipet',
    'Suryapet',
    'Vikarabad',
    'Wanaparthy',
    'Warangal',
    'Yadadri Bhuvanagiri',
  ],

  // Tripura (8 districts)
  'Tripura': [
    'Dhalai',
    'Gomati',
    'Khowai',
    'North Tripura',
    'Sepahijala',
    'South Tripura',
    'Unakoti',
    'West Tripura',
  ],

  // Uttar Pradesh (75 districts)
  'Uttar Pradesh': [
    'Agra',
    'Aligarh',
    'Ambedkar Nagar',
    'Amethi',
    'Amroha',
    'Auraiya',
    'Ayodhya',
    'Azamgarh',
    'Baghpat',
    'Bahraich',
    'Ballia',
    'Balrampur',
    'Banda',
    'Barabanki',
    'Bareilly',
    'Basti',
    'Bhadohi',
    'Bijnor',
    'Budaun',
    'Bulandshahr',
    'Chandauli',
    'Chitrakoot',
    'Deoria',
    'Etah',
    'Etawah',
    'Farrukhabad',
    'Fatehpur',
    'Firozabad',
    'Gautam Buddha Nagar',
    'Ghaziabad',
    'Ghazipur',
    'Gonda',
    'Gorakhpur',
    'Hamirpur',
    'Hapur',
    'Hardoi',
    'Hathras',
    'Jalaun',
    'Jaunpur',
    'Jhansi',
    'Kannauj',
    'Kanpur Dehat',
    'Kanpur Nagar',
    'Kasganj',
    'Kaushambi',
    'Kushinagar',
    'Lakhimpur Kheri',
    'Lalitpur',
    'Lucknow',
    'Maharajganj',
    'Mahoba',
    'Mainpuri',
    'Mathura',
    'Mau',
    'Meerut',
    'Mirzapur',
    'Moradabad',
    'Muzaffarnagar',
    'Pilibhit',
    'Pratapgarh',
    'Prayagraj',
    'Rae Bareli',
    'Rampur',
    'Saharanpur',
    'Sambhal',
    'Sant Kabir Nagar',
    'Shahjahanpur',
    'Shamli',
    'Shravasti',
    'Siddharthnagar',
    'Sitapur',
    'Sonbhadra',
    'Sultanpur',
    'Unnao',
    'Varanasi',
  ],

  // Uttarakhand (13 districts)
  'Uttarakhand': [
    'Almora',
    'Bageshwar',
    'Chamoli',
    'Champawat',
    'Dehradun',
    'Haridwar',
    'Nainital',
    'Pauri Garhwal',
    'Pithoragarh',
    'Rudraprayag',
    'Tehri Garhwal',
    'Udham Singh Nagar',
    'Uttarkashi',
  ],

  // West Bengal (23 districts)
  'West Bengal': [
    'Alipurduar',
    'Bankura',
    'Birbhum',
    'Cooch Behar',
    'Dakshin Dinajpur',
    'Darjeeling',
    'Hooghly',
    'Howrah',
    'Jalpaiguri',
    'Jhargram',
    'Kalimpong',
    'Kolkata',
    'Malda',
    'Murshidabad',
    'Nadia',
    'North 24 Parganas',
    'Paschim Bardhaman',
    'Paschim Medinipur',
    'Purba Bardhaman',
    'Purba Medinipur',
    'Purulia',
    'South 24 Parganas',
    'Uttar Dinajpur',
  ],

  // ── Union Territories ──────────────────────────────────────────────────────

  // Andaman & Nicobar Islands (3 districts)
  'Andaman & Nicobar Islands': [
    'Nicobars',
    'North & Middle Andaman',
    'South Andaman',
  ],

  // Chandigarh (1 district)
  'Chandigarh': [
    'Chandigarh',
  ],

  // Dadra & Nagar Haveli and Daman & Diu (3 districts)
  'Dadra & Nagar Haveli and Daman & Diu': [
    'Dadra & Nagar Haveli',
    'Daman',
    'Diu',
  ],

  // Delhi (11 districts)
  'Delhi': [
    'Central Delhi',
    'East Delhi',
    'New Delhi',
    'North Delhi',
    'North East Delhi',
    'North West Delhi',
    'Shahdara',
    'South Delhi',
    'South East Delhi',
    'South West Delhi',
    'West Delhi',
  ],

  // Jammu & Kashmir (20 districts)
  'Jammu & Kashmir': [
    'Anantnag',
    'Bandipora',
    'Baramulla',
    'Budgam',
    'Doda',
    'Ganderbal',
    'Jammu',
    'Kathua',
    'Kishtwar',
    'Kulgam',
    'Kupwara',
    'Poonch',
    'Pulwama',
    'Rajouri',
    'Ramban',
    'Reasi',
    'Samba',
    'Shopian',
    'Srinagar',
    'Udhampur',
  ],

  // Ladakh (2 districts)
  'Ladakh': [
    'Kargil',
    'Leh',
  ],

  // Lakshadweep (1 district)
  'Lakshadweep': [
    'Lakshadweep',
  ],

  // Puducherry (4 districts)
  'Puducherry': [
    'Karaikal',
    'Mahé',
    'Puducherry',
    'Yanam',
  ],
};

// ─── UPSC CMS Exam Centres (48 centres — August 2026 notification) ────────────
// The centre name is stored in `exam_centre_district`; its parent state/UT in
// `exam_centre_state`. `exam_center` (free text) is left null for CMS profiles.
export type CmsCentre = { centre: string; state: string };

export const UPSC_CMS_CENTRES: CmsCentre[] = [
  { centre: 'Agartala', state: 'Tripura' },
  { centre: 'Ahmedabad', state: 'Gujarat' },
  { centre: 'Aizawl', state: 'Mizoram' },
  { centre: 'Bareilly', state: 'Uttar Pradesh' },
  { centre: 'Bengaluru', state: 'Karnataka' },
  { centre: 'Bhopal', state: 'Madhya Pradesh' },
  { centre: 'Bhubaneswar', state: 'Odisha' },
  { centre: 'Chandigarh', state: 'Chandigarh' },
  { centre: 'Chennai', state: 'Tamil Nadu' },
  { centre: 'Cuttack', state: 'Odisha' },
  { centre: 'Dehradun', state: 'Uttarakhand' },
  { centre: 'Delhi', state: 'Delhi' },
  { centre: 'Dharwad', state: 'Karnataka' },
  { centre: 'Dispur', state: 'Assam' },
  { centre: 'Faridabad', state: 'Haryana' },
  { centre: 'Gangtok', state: 'Sikkim' },
  { centre: 'Gautam Buddha Nagar (Noida)', state: 'Uttar Pradesh' },
  { centre: 'Ghaziabad', state: 'Uttar Pradesh' },
  { centre: 'Gurugram', state: 'Haryana' },
  { centre: 'Hyderabad', state: 'Telangana' },
  { centre: 'Imphal', state: 'Manipur' },
  { centre: 'Itanagar', state: 'Arunachal Pradesh' },
  { centre: 'Jaipur', state: 'Rajasthan' },
  { centre: 'Jammu', state: 'Jammu & Kashmir' },
  { centre: 'Jorhat', state: 'Assam' },
  { centre: 'Kanpur', state: 'Uttar Pradesh' },
  { centre: 'Kochi', state: 'Kerala' },
  { centre: 'Kohima', state: 'Nagaland' },
  { centre: 'Kolkata', state: 'West Bengal' },
  { centre: 'Lucknow', state: 'Uttar Pradesh' },
  { centre: 'Madurai', state: 'Tamil Nadu' },
  { centre: 'Meerut', state: 'Uttar Pradesh' },
  { centre: 'Mumbai', state: 'Maharashtra' },
  { centre: 'Nagpur', state: 'Maharashtra' },
  { centre: 'Panaji (Goa)', state: 'Goa' },
  { centre: 'Patna', state: 'Bihar' },
  { centre: 'Sri Vijaya Puram (Port Blair)', state: 'Andaman & Nicobar Islands' },
  { centre: 'Prayagraj', state: 'Uttar Pradesh' },
  { centre: 'Raipur', state: 'Chhattisgarh' },
  { centre: 'Ranchi', state: 'Jharkhand' },
  { centre: 'Sambalpur', state: 'Odisha' },
  { centre: 'Shillong', state: 'Meghalaya' },
  { centre: 'Shimla', state: 'Himachal Pradesh' },
  { centre: 'Srinagar', state: 'Jammu & Kashmir' },
  { centre: 'Thiruvananthapuram', state: 'Kerala' },
  { centre: 'Tirupati', state: 'Andhra Pradesh' },
  { centre: 'Udaipur', state: 'Rajasthan' },
  { centre: 'Visakhapatnam', state: 'Andhra Pradesh' },
];

// ─── Cascade / lookup helpers (pure) ──────────────────────────────────────────

/** Districts for a state/UT (empty array if the state is unknown or blank). */
export function districtsFor(state: string | null | undefined): string[] {
  if (!state) return [];
  return DISTRICTS_BY_STATE[state] ?? [];
}

/** The 48 UPSC CMS centre names, in notification order (for a centre picker). */
export function cmsCentres(): string[] {
  return UPSC_CMS_CENTRES.map((c) => c.centre);
}

/** Parent state/UT for a UPSC CMS centre name, or null if unknown. */
export function getCmsCentreState(centreName: string | null | undefined): string | null {
  if (!centreName) return null;
  return UPSC_CMS_CENTRES.find((c) => c.centre === centreName)?.state ?? null;
}

/** STATES alphabetised (the web sorts before rendering the picker). */
export function statesSorted(): string[] {
  return [...STATES].sort((a, b) => a.localeCompare(b));
}
